/** Item 66: the provider's callable surface, generated from its methods. Fields come
 * from `ProviderState` rather than being repeated here, so a field's type is the one
 * the class really initializes. `provider-registry.test.ts` asserts every member is
 * installed on the prototype, so this type cannot promise more than it delivers. */

import { activateRestrictedWorkspace } from "./restricted.ts";
import { showArtifacts } from "./artifacts.ts";
/*
 * Cedia's Mac extension boundary.
 *
 * This extension talks to the Cedia host over its authenticated HTTP API.  It
 * intentionally has no OMP process launcher: OMP belongs to the host and the
 * host descriptor is the only way this client discovers a running session.
 */

import * as vscode from "vscode";
import { randomBytes, randomUUID } from "node:crypto";
import { spawn, type ChildProcess } from "node:child_process";
import { existsSync } from "node:fs";
import { homedir } from "node:os";
import { basename, isAbsolute, join, relative, resolve } from "node:path";
import { promisify } from "node:util";
import { CediaHostClient, HostDescriptorError, HostHttpError, HostRequestTimeoutError } from "./api.ts";
import type { NativeAction } from "./messages.ts";
import { createInitialTaskState, normalizeSlashCommands, parseCediaUiRequest, reduceTaskState, type LoginProviderOption, type ModelOption, type TaskState } from "./state.ts";
import { CediaIdeAgentProvider } from "./agent-ide-webview.ts";
import { writeAgentThemeSnapshot } from "./agent-theme.ts";
import { fetchGlobalOmpModelSnapshot, fetchOmpModelRoles } from "./omp-catalog.ts";
import { currentModelFromOmpState, modelRoleLabel, sessionIdFromUri, setModelRoleRequest } from "./chat-sessions-map.ts";
import { canAnswer } from "./approval-runtime.ts";
import { approvalCanSubmit, approvalDisplayStatus } from "./approval-view.ts";
import type { ArtifactReceipt } from "../../../packages/protocol/src/artifacts.ts";
import { ompSettingsCatalog, SETTINGS_SECTIONS } from "./capability-catalog.ts";
import { composerAxesFromTask, resolveComposerControls } from "./composer-runtime.ts";
import { isCediaWorkbenchPalette } from "./cedia-theme.ts";
import { shouldDispatch, type FrozenEnvelope } from "./dispatch-guard.ts";
import { recoveryBanner } from "./recovery-ui.ts";
import { DISCARD_DRAFT_CONFIRM, discardDraftPlan } from "./discard-draft.ts";
import { aboutIdentity } from "./about-identity.ts";
import { alreadyAttached, reduceAttachment, type Attachment } from "./attachment-runtime.ts";
import { buildSubagentTree, emptyPlan, planFromOmpState, type PlanProjection } from "./plan-projection.ts";
import { BRANCH_SELECT_REASON, branchHitsFromHostBranches, type BranchHit } from "./branch-picker.ts";
import { providerGlyphMap } from "./provider-icons.ts";
import { emptyReview, ideLandingForWorkTab, markReviewDirtyConflict, markReviewStale, parseUnifiedDiff, REVIEW_CONFLICT_REASON, reviewCommitPreview, reviewFromGitStatus, reviewOpenMergeEnabled, reviewSummary, reviewWorkspaceLabel, type ReviewSnapshot } from "./review-snapshot.ts";
import { buildSearchHits, emptySearchPalette, SEARCH_INDEX_FAILED_NOTE, type SearchPaletteState } from "./search-palette.ts";
import { applyProductPref, clampSidebarWidth, DEFAULT_PRODUCT_PREFS, isProductPrefSettingKey, normalizeProductPrefs, type ProductPrefs } from "./product-prefs.ts";
import { canInlinePreviewBytes, inlinePreviewMime, mapArtifactsForWebview, type ArtifactPreview } from "./artifact-preview.ts";
import { downloadArtifact } from "./artifact-transfer.ts";
import { applySessionFilters, DEFAULT_SIDEBAR_FILTERS, filterChips, filterEmptyCopy, markAllAsReadScope, normalizeSidebarFilters, type SidebarFilters } from "./sidebar-filters.ts";
import { cediaWindowTitle, FORK_NO_PARENT_REASON, moreMenuActions, NEED_MORE_SPACE_REASON, taskHeaderMeta, type MoreMenuActionId } from "./task-chrome.ts";
import { MISSING_RECENT_REASON, projectAddPlan, projectsWelcomeModel } from "./projects-welcome.ts";
import { parseSuggestionPayload, SUGGEST_ENDPOINT } from "./browser-search.ts";
import { focusUserPtyPlan, newUserPtyPlan, userPtyRows } from "./user-pty.ts";
import { activeLeaf, assignActive, canSplit, closeActive, createLayoutTree, focusView, layoutLeaves, maximizeActive, moveActive, openSessionInSplit, paneDraftKey, parseLayout, restoreLayout, serializeLayout, splitActive, visibleLeaves, type LayoutTree } from "./layout-tree.ts";
import { layoutBoxes, layoutSashes, setSplitRatio } from "./layout-geometry.ts";
import { buildPaneViews, rememberPaneTranscript, type PaneTranscriptCache, type PaneView } from "./pane-views.ts";
import { announceSummary, motionTokens } from "./ui-a11y.ts";
import { redactedDiagnostics } from "./diagnostics.ts";
import { AGENTS_WINDOW_WORKSPACE, themeProvidingExtensionIds, consumePendingNativeDestination, DEFAULT_IDE_LAYOUT, draftViewKey, isAgentsWindow, mergeAgentsWindowWorkspaceSettings, modeSwitchProof, normalizeIdeLayout, persistDestinationAcrossReload, queuePendingNativeDestination, rememberIdeChrome, resolveSnapshotThemeName, resolveStartupView, retentionReceipt, runWorkbenchCommands, switchWorkbenchMode, type IdeLayoutSnapshot, type NativeDestination, type RetentionSnapshot } from "./workbench-mode.ts";
import { availabilityFromLists, routeErrorPage, validateRoute, type RouteErrorPage } from "./route-error.ts";
import { applySettingsSection, beginSettingsDraft, previewResetOverride, settingsSourcePath, type ResetOverridePreview, type SettingsSectionDraft } from "./settings-revision.ts";
import { OLDER_PAGES_NOTE } from "./history-page.ts";
import { CLOUD_DESTINATION_REASON, destinationOptions, RELAY_UNKNOWN_REASON, WORKTREE_NO_GIT_REASON } from "./destination-picker.ts";
import { mentionRows } from "./mention-context.ts";
import { bindSettingsCatalogRows, jsonPickerCommands, skillsFromSlashCommands } from "./settings-catalog-rows.ts";
import { shortcutRowsFromContributes } from "./shortcut-rows.ts";
import { canRouteBack, canRouteForward, emptyRouteHistory, rememberRoute, routeBack, routeForward, type RouteFrame, type RouteHistory } from "./route-stack.ts";
import { emptyThinkingParams, messagesPageFromOmp, ompCommandData, parentSessionFromOmpState, THINKING_NOT_ADVERTISED, thinkingFromOmpState, type ThinkingParams } from "./thinking-params.ts";
import { FORK_NOT_CREATED_REASON, ompCommandConfirmed, THINKING_NOT_APPLIED_REASON } from "./omp-result.ts";
import { transcriptEntriesFromOmpMessages } from "./transcript-page.ts";
import { resolveShellLayout, visibleWorkResources, workResourceId, WORK_PANEL_TABS, type ResourceStatus, type WorkPanelTab } from "./work-panel.ts";
import { projectSessionFilterFields } from "./session-row-meta.ts";
import { beginWorktreeReceipt, cancelWorktreeReceipt, failedWorktreeReceipt, idleWorktreeReceipt, readyWorktreeReceipt, type WorktreeReceipt } from "./worktree-receipt.ts";
import { CediaEditorService, type EditorAppliedSummary } from "./editor.ts";
import { AGENT_EDIT_DIFF_SCHEME, agentEditDiffTitle, decodeAgentEditDocId, decodeReviewDocId, encodeAgentEditDocId, encodeReviewDocId, looksBinary, NATIVE_DIFF_BINARY_REASON, NATIVE_DIFF_SCHEME, nativeDiffPlan, resolveReviewTarget } from "./native-diff.ts";
import { cediaCodeActions } from "./code-actions.ts";
import { agentEditLabel, agentEditLenses, agentEditReviewDecision, decorationHover, decorationRange, markRangesFor, revertDecision, type MarkRange, type PendingAgentEdit } from "./agent-edit-marks.ts";
import { selectionAction, selectionPrompt, type SelectionActionId } from "./selection-actions.ts";
import { MAX_TERMINAL_CITATION_CHARS, TERMINAL_NOT_FOCUSED_REASON, terminalCitation } from "./terminal-context.ts";
import { PendingFocus, ViewRegistry } from "./view-registry.ts";
import { RPC_COMMAND_TYPES } from "../../../packages/omp-adapter/src/types.ts";
import QRCode from "qrcode";
import { OmpTerminalViews } from "./terminal.ts";
import type { Command, Json, Project, Session } from "../../../packages/protocol/src/index.ts";


import type { ProviderState } from "./provider-state.ts";
import { normalizeSession } from "./task-runtime.ts";

export interface CediaTaskViewProviderMethods {
	getStateForTest(): { draft: string };
	getWorkPanelForTest(): { open: boolean; activeTab: string };
	resolveWebviewView(view: vscode.WebviewView): void;
	openAgentsWindow(): void;
	showIde(): void;
	revealAgentSurface(): Promise<void>;
	captureIdeLayout(): IdeLayoutSnapshot;
	applyWorkbenchAppearance(mode: "agents" | "ide"): Promise<void>;
	reapplyWorkbenchAppearance(): void;
	inAgentsWindow(): boolean;
	rememberIdeFolder(): Promise<void>;
	openIdeWindow(): Promise<void>;
	setWorkbenchMode(mode: "agents" | "ide", opts?: { readonly newWindow?: boolean }): Promise<void>;
	attachmentRefs(): readonly string[];
	retentionSnapshot(mode: "agents" | "ide"): RetentionSnapshot;
	persistModeSwitchProof(to: "agents" | "ide"): void;
	focusComposer(): void;
	focusSearch(): void;
	skipToTask(): void;
	focusAgentSurface(message: unknown): Promise<void>;
	refreshNow(): Promise<void>;
	setProjectPinned(folderPath: unknown): Promise<void>;
	configureModelRoles(): Promise<void>;
	renameProject(folderPath: unknown): Promise<void>;
	archiveProjectChats(folderPath: unknown): Promise<void>;
	removeProject(folderPath: unknown): Promise<void>;
	deleteChatSessions(hint: unknown): Promise<void>;
	createWorktreeForProject(folderPath: unknown): Promise<void>;
	resolveHostProject(hint: string, client: CediaHostClient): Promise<Project | undefined>;
	withHostProject(hint: unknown, run: (project: Project, client: CediaHostClient) => Promise<void>): Promise<void>;
	revealProject(hint: unknown): Promise<void>;
	prefill(text: string): void;
	post(message: unknown): void;
	postSnapshot(): void;
	currentMentions(): ReturnType<typeof mentionRows>;
	currentSettingsRows(): ReturnType<typeof bindSettingsCatalogRows>;
	activeScrollKey(): string;
	scrollKeyForView(viewId?: string): string;
	applyStartupView(): void;
	applyWindowTitle(): void;
	setState(action: Parameters<typeof reduceTaskState>[1]): void;
	currentRouteFrame(): RouteFrame;
	rememberCurrentRoute(): void;
	applyRouteFrame(frame: RouteFrame): Promise<void>;
	openProjectsRoute(): Promise<void>;
	goRouteBack(): Promise<void>;
	goRouteForward(): Promise<void>;
	reportError(error: unknown): void;
	ensureClient(): Promise<CediaHostClient>;
	syncIdeSession(id: string): Promise<void>;
	startPolling(): void;
	pollEditor(): Promise<void>;
	pullEvents(): Promise<void>;
	refresh(): Promise<void>;
	refreshGitBranch(): Promise<void>;
	loadProjectSessions(client: CediaHostClient, project: Project): Promise<void>;
	ensureProject(client: CediaHostClient): Promise<Project>;
	ensureSession(client: CediaHostClient): Promise<Session>;
	requestOmp(command: string, payload?: Record<string, Json>): Promise<Command | undefined>;
	refreshOmpState(): Promise<void>;
	loadOlderMessages(): Promise<void>;
	selectThinkingLevel(level: string): Promise<void>;
	sendCommand(command: string, payload: Record<string, Json>): Promise<void>;
	answerUi(token: string, answer: string | boolean | readonly string[] | { cancelled: true; timedOut?: boolean }): Promise<void>;
	newTaskFlow(): Promise<void>;
	openFolderFlow(): Promise<void>;
	addProjectFlow(): Promise<void>;
	suggestSearchTerms(term: unknown): Promise<string[]>;
	addProjectAtPath(path: string): Promise<void>;
	welcomeModel(): ReturnType<typeof projectsWelcomeModel>;
	rememberRecent(path: string): Promise<void>;
	persistLayout(): void;
	persistLegacyDrafts(): Promise<void>;
	setWorkResource(tab: WorkPanelTab, status: ResourceStatus, detail?: string): void;
	expireWorkResource(tab: WorkPanelTab): void;
	restartWorkResource(tab: WorkPanelTab): Promise<void>;
	activatePane(viewId?: string): Promise<void>;
	rememberActiveTranscript(): void;
	captureActivePaneDraft(): void;
	applyActivePaneDraft(): void;
	syncSinglePaneIdentity(): void;
	openProjectAtPath(path: string): Promise<void>;
	applyPaneSplit(direction: "right" | "down"): void;
	openSessionInNewPane(sessionId: string): Promise<void>;
	applyClosePane(): void;
	revealActivePane(): Promise<void>;
	createWorktreeOnCurrentProject(): Promise<void>;
	startCreatedSession(id: string, created: ReturnType<typeof normalizeSession>): Promise<void>;
	routeAvailability(): ReturnType<typeof availabilityFromLists>;
	showRouteError(error: RouteErrorPage): void;
	selectProject(id: string): Promise<void>;
	selectSession(id: string, fromHistory?: boolean): Promise<void>;
	selectModel(modelId: string, provider?: string): Promise<void>;
	getModels(): Promise<void>;
	getLoginProviders(): Promise<void>;
	getSlashCommands(): Promise<void>;
	startLogin(providerId: string): Promise<void>;
	openLoginUrl(url: string): Promise<void>;
	nativeAction(action: NativeAction): Promise<void>;
	refreshReview(): Promise<void>;
	refreshArtifacts(): Promise<void>;
	refreshDevices(): Promise<void>;
	pickAttachments(): Promise<void>;
	reviewFile(path: string): Promise<void>;
	applyDirtyConflict(): Promise<void>;
	openWorkspaceFile(path: string): Promise<void>;
	openMergeEditor(path: string): Promise<void>;
	pairDevice(): Promise<void>;
	manageDevices(): Promise<void>;
	ompControls(): Promise<void>;
	openCediaSettings(): Promise<void>;
	ompSignIn(): Promise<void>;
	runMoreAction(id: string): Promise<void>;
	inspectOutcome(): Promise<void>;
	taskActions(): Promise<void>;
	sessionForMutation(sessionId?: string): Session | undefined;
	patchListedSession(sessionId: string | undefined, apply: (session: Session, client: CediaHostClient) => Promise<void>): Promise<void>;
	handleMessage(_message: unknown): Promise<void>;
	selectDestination(id: string): Promise<void>;
	appendContextBlock(block: string, citation: string, focus: boolean): Promise<boolean>;
	appendActiveEditorContext(opts: { readonly requireSelection: boolean; readonly focus: boolean; /** Explicit target, used by the Explorer context menu. Defaults to the active editor. */ readonly uri?: vscode.Uri; }): Promise<boolean>;
	addSelectionToTask(): Promise<void>;
	addTerminalSelectionToTask(): Promise<void>;
	codeActionsFor(document: vscode.TextDocument, range: vscode.Range): vscode.CodeAction[];
	runSelectionAction(id: SelectionActionId): Promise<void>;
	recordAgentEdit(summary: EditorAppliedSummary): void;
	agentEditDecorationType(): vscode.TextEditorDecorationType;
	refreshAgentEditMarks(): void;
	agentEditDecoration(document: vscode.TextDocument, range: MarkRange, pending: PendingAgentEdit): vscode.DecorationOptions;
	keepAgentEdit(): Promise<void>;
	revertAgentEdit(): Promise<void>;
	reviewAgentEdit(): Promise<void>;
	agentEditLensesFor(document: vscode.TextDocument): vscode.CodeLens[];
	agentEditLensesProvider(): vscode.CodeLensProvider;
	forgetAgentEdit(uri: string, message: string): void;
	inlineEdit(): Promise<void>;
	addFileToTask(resource?: vscode.Uri): Promise<void>;
	focusDock(): Promise<void>;
	diffContentProvider(): vscode.TextDocumentContentProvider;
	reviewCwd(): string | undefined;
	agentEditBeforeProvider(): vscode.TextDocumentContentProvider;
	gitOriginalText(cwd: string, ref: string, path: string): Promise<string>;
	gitPathIsBinary(cwd: string, path: string): Promise<boolean>;
	openNativeDiff(path: string): Promise<void>;
	reviewActiveFileInDiff(resource?: vscode.Uri): Promise<void>;
	renderAgentsStatus(): void;
	hasTaskSurface(): boolean;
	syncCediaContext(): void;
	pickMention(kind: "file" | "folder" | "selection" | "logs" | "artifacts" | "session", _id: string): Promise<void>;
	downloadArtifactCopy(sha256: string): Promise<void>;
	exportDiagnostics(): Promise<void>;
	dispose(): void;
}

export type CediaTaskViewProviderApi = ProviderState & CediaTaskViewProviderMethods;
